server:
  port: 8080
  context-path: /ant/school
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ant?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mappings/*/*.xml
  type-aliases-package: com.ant.school

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
